export const Ratings = [
  { value: '3.5', label: '3.5', genitiveLabel: '' /* 4631 */ },
  { value: null, label: 'Без оценки', genitiveLabel: '' /* 3773 */ },
  { value: 'R', label: 'R', genitiveLabel: '' /* 2519 */ },
  { value: '4', label: '4', genitiveLabel: '' /* 2498 */ },
  { value: '3', label: '3', genitiveLabel: '' /* 1598 */ },
  { value: '4.5', label: '4.5', genitiveLabel: '' /* 1280 */ },
  { value: '5', label: '5', genitiveLabel: '' /* 529 */ },
  { value: 'RA', label: 'RA', genitiveLabel: '' /* 501 */ },
  { value: '2', label: '2', genitiveLabel: '' /* 185 */ },
  { value: '0', label: '0', genitiveLabel: '' /* 179 */ },
  { value: 'S', label: 'S', genitiveLabel: '' /* 163 */ },
  { value: '6', label: '6', genitiveLabel: '' /* 136 */ },
  { value: 'X', label: 'X', genitiveLabel: '' /* 57 */ },
  { value: '99', label: '99', genitiveLabel: '' /* 50 */ },
  { value: 'RB', label: 'RB', genitiveLabel: '' /* 38 */ },
  { value: 'N', label: 'N', genitiveLabel: '' /* 13 */ },
  { value: 'G', label: 'G', genitiveLabel: '' /* 12 */ },
  { value: '1', label: '1', genitiveLabel: '' /* 11 */ },
  { value: 'W', label: 'W', genitiveLabel: '' /* 8 */ },
  { value: 'B', label: 'B', genitiveLabel: '' /* 7 */ },
  { value: 'R1', label: 'R1', genitiveLabel: '' /* 1 */ },
]
