/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    'user-profile': UserProfileAuthOperations;
  };
  blocks: {};
  collections: {
    'user-profile': UserProfile;
    'user-request': UserRequest;
    'review-card': ReviewCard;
    'catalog-car': CatalogCar;
    'exchange-rate': ExchangeRate;
    'auction-media': AuctionMedia;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    'user-profile': UserProfileSelect<false> | UserProfileSelect<true>;
    'user-request': UserRequestSelect<false> | UserRequestSelect<true>;
    'review-card': ReviewCardSelect<false> | ReviewCardSelect<true>;
    'catalog-car': CatalogCarSelect<false> | CatalogCarSelect<true>;
    'exchange-rate': ExchangeRateSelect<false> | ExchangeRateSelect<true>;
    'auction-media': AuctionMediaSelect<false> | AuctionMediaSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: UserProfile & {
    collection: 'user-profile';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserProfileAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-profile".
 */
export interface UserProfile {
  id: string;
  name: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-request".
 */
export interface UserRequest {
  id: string;
  type: 'CAR_SELECTION' | 'CALLBACK';
  name: string;
  tel: string;
  email?: string | null;
  issue?: string | null;
  car?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "review-card".
 */
export interface ReviewCard {
  id: string;
  name: string;
  shortText: string;
  externalLink: string;
  images: string | AuctionMedia;
  countStars?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auction-media".
 */
export interface AuctionMedia {
  id: string;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "catalog-car".
 */
export interface CatalogCar {
  id: string;
  images?: (string | AuctionMedia)[] | null;
  auctionList?: (string | null) | AuctionMedia;
  externalId: string;
  lot: number;
  auction: string;
  brand: string;
  body?: string | null;
  model: string;
  modelDisplay: string;
  modelSlug: string;
  year: number;
  wheelPosition?: ('right' | 'left') | null;
  transmission?: string | null;
  enginePower?: number | null;
  horsepower?: number | null;
  driveType?: string | null;
  rating?: string | null;
  price: {
    currency?: string | null;
    start?: number | null;
    final?: number | null;
    avg?: number | null;
    avgList?: number[] | null;
  };
  customsDuty?: {
    individual?: number | null;
    legalEntity?: number | null;
  };
  disposalFee?: {
    individual?: number | null;
    legalEntity?: number | null;
  };
  saleCountry?: ('JAPAN' | 'CHINA') | null;
  engineType?: ('gasoline' | 'diesel' | 'electric' | 'hybrid-gasoline' | 'hybrid-diesel') | null;
  mileageKm?: number | null;
  date: string;
  color?: string | null;
  saleStatus?: string | null;
  isSold?: boolean | null;
  isSanctions?: boolean | null;
  isFinish?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exchange-rate".
 */
export interface ExchangeRate {
  id: string;
  title?: string | null;
  fromCurrency: string;
  toCurrency: string;
  rate: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'user-profile';
        value: string | UserProfile;
      } | null)
    | ({
        relationTo: 'user-request';
        value: string | UserRequest;
      } | null)
    | ({
        relationTo: 'review-card';
        value: string | ReviewCard;
      } | null)
    | ({
        relationTo: 'catalog-car';
        value: string | CatalogCar;
      } | null)
    | ({
        relationTo: 'exchange-rate';
        value: string | ExchangeRate;
      } | null)
    | ({
        relationTo: 'auction-media';
        value: string | AuctionMedia;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'user-profile';
    value: string | UserProfile;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'user-profile';
    value: string | UserProfile;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-profile_select".
 */
export interface UserProfileSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-request_select".
 */
export interface UserRequestSelect<T extends boolean = true> {
  type?: T;
  name?: T;
  tel?: T;
  email?: T;
  issue?: T;
  car?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "review-card_select".
 */
export interface ReviewCardSelect<T extends boolean = true> {
  name?: T;
  shortText?: T;
  externalLink?: T;
  images?: T;
  countStars?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "catalog-car_select".
 */
export interface CatalogCarSelect<T extends boolean = true> {
  images?: T;
  auctionList?: T;
  externalId?: T;
  lot?: T;
  auction?: T;
  brand?: T;
  body?: T;
  model?: T;
  modelDisplay?: T;
  modelSlug?: T;
  year?: T;
  wheelPosition?: T;
  transmission?: T;
  enginePower?: T;
  horsepower?: T;
  driveType?: T;
  rating?: T;
  price?:
    | T
    | {
        currency?: T;
        start?: T;
        final?: T;
        avg?: T;
        avgList?: T;
      };
  customsDuty?:
    | T
    | {
        individual?: T;
        legalEntity?: T;
      };
  disposalFee?:
    | T
    | {
        individual?: T;
        legalEntity?: T;
      };
  saleCountry?: T;
  engineType?: T;
  mileageKm?: T;
  date?: T;
  color?: T;
  saleStatus?: T;
  isSold?: T;
  isSanctions?: T;
  isFinish?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exchange-rate_select".
 */
export interface ExchangeRateSelect<T extends boolean = true> {
  title?: T;
  fromCurrency?: T;
  toCurrency?: T;
  rate?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auction-media_select".
 */
export interface AuctionMediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}